### ISSUE TITLE
Add a campaign on the sun and moon

### ISSUE THREAD

**Issue by LordDennis18** [RebornTrack970/moonmod#1]
Here's my idea on the sun:

-all of the sectors contains slag 
-some of them also contains magma rock and hot rock just like the dark spots on our sun
-contains dried out rock which is the dark spot of the sun
-abandoned bases like someone has already visited the sun
-new type of ore (sun ore, sunstone, raydium)

My ideas for the moon:
-all sectors contains craters, stone and char as the surface of the moon
-boulders, new ores (moon ore, moonstone), new environments
-moon base maybe an ally or an enemy base
-new weather system falling asteroids once in a time an asteroid would fall out in the sky

**Comment by RebornTrack970** [comment]
This mod wasnt sposed to add sectors to sun.
Moon is fully for the effect, it is decorative. It is just tantros but small.
